# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='date of birth')),
                ('social_networks', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin', models.BooleanField(default=False)),
                ('curator', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
