# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_users', '0001_initial'),
        ('v1_themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.FloatField(default=0, verbose_name='course rating')),
                ('date_created', models.DateField(editable=False, verbose_name='date of creation')),
                ('lesson_num', models.IntegerField(default=0, verbose_name='number of lessons')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='last update')),
                ('curator', models.ManyToManyField(related_name='course_curator', to='v1_users.User')),
                ('listener', models.ManyToManyField(related_name='listener', to='v1_users.User')),
                ('theme', models.ManyToManyField(related_name='theme', to='v1_themes.Theme')),
            ],
        ),
    ]
