# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(editable=False, verbose_name='date of creation')),
                ('materials_num', models.IntegerField(blank=True, null=True, verbose_name='number of materials')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='last update')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.course')),
            ],
        ),
    ]
