# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_users', '0001_initial'),
        ('v1_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_uncompleted', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(related_name='course_action', to='v1_courses.Course')),
                ('listener', models.ManyToManyField(related_name='course_action_listener', to='v1_users.User')),
            ],
        ),
    ]
