# Generated by Django 3.2.3 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_users', '0001_initial'),
        ('v1_lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='text of comment')),
                ('date', models.DateTimeField(verbose_name='date of adding')),
                ('lesson', models.ManyToManyField(related_name='comment_to_lesson', to='v1_lessons.Lesson')),
                ('listener', models.ManyToManyField(related_name='listener_comment', to='v1_users.User')),
            ],
        ),
    ]
