# Generated by Django 3.1.7 on 2021-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210227_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_of_creation',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
