# Generated by Django 3.2.3 on 2021-05-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_tasks', '0001_initial'),
        ('v1_materials', '0001_initial'),
        ('v1_lessons', '0001_initial'),
        ('v1_lesson_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaction',
            name='last_lesson',
            field=models.ManyToManyField(blank=True, related_name='last_lesson', to='v1_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='lessonaction',
            name='last_task',
            field=models.ManyToManyField(blank=True, related_name='last_task', to='v1_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='lessonaction',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='lesson_action', to='v1_lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonaction',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='material_action', to='v1_materials.Material'),
        ),
        migrations.AlterField(
            model_name='lessonaction',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='task_action', to='v1_tasks.Task'),
        ),
    ]
